server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://product-db:13307/${PRODUCT_MYSQL_DATABASE}
    username: ${PRODUCT_MYSQL_USERNAME}
    password: ${PRODUCT_MYSQL_PASSWORD}
  data:
    redis:
      host: my-cache-server
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        step: 5s